import type { Ability } from "./types";

// Poderes de teste (personagem genérico) — só pra validar o sistema.
// Poderes de anime de verdade entram aqui depois, como novas receitas.
export const ABILITIES = {
  bolaDeEnergia: {
    id: "bolaDeEnergia",
    name: "Bola de Energia",
    tier: "common",
    cost: 20,
    cooldownMs: 3000,
    target: { kind: "projectile", speed: 25 },
    effect: [{ kind: "damage", amount: 25 }],
    vfx: { color: "#4fa3ff", particle: "spark", sound: "whoosh" },
  },
  golpeRapido: {
    id: "golpeRapido",
    name: "Golpe Rápido",
    tier: "common",
    cost: 10,
    cooldownMs: 1500,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 12 }],
    vfx: { color: "#ffffff", sound: "hit" },
  },
  ondaDeChoque: {
    id: "ondaDeChoque",
    name: "Onda de Choque",
    tier: "strong",
    cost: 40,
    cooldownMs: 8000,
    target: { kind: "area", radius: 5 },
    effect: [{ kind: "stun", durationMs: 1200 }],
    vfx: { color: "#ffb347", particle: "shock" },
  },
  passoRapido: {
    id: "passoRapido",
    name: "Passo Rápido",
    tier: "strong",
    cost: 15,
    cooldownMs: 6000,
    target: { kind: "self" },
    effect: [{ kind: "speedBuff", factor: 1.5, durationMs: 2000 }],
    vfx: { color: "#7dffb3", particle: "trail" },
  },
  explosaoDefinitiva: {
    id: "explosaoDefinitiva",
    name: "Explosão Definitiva",
    tier: "super",
    cost: 100,
    cooldownMs: 45000,
    target: { kind: "area", radius: 10 },
    effect: [{ kind: "damage", amount: 80 }],
    vfx: { color: "#ff3b3b", particle: "nova", sound: "boom" },
  },
  rajadaDeGelo: {
    id: "rajadaDeGelo",
    name: "Rajada de Gelo",
    tier: "common",
    cost: 15,
    cooldownMs: 4000,
    target: { kind: "projectile", speed: 20 },
    effect: [{ kind: "slow", factor: 0.5, durationMs: 2000 }],
    vfx: { color: "#8fe8ff", particle: "frost", sound: "chill" },
  },
  curaRapida: {
    id: "curaRapida",
    name: "Cura Rápida",
    tier: "common",
    cost: 25,
    cooldownMs: 5000,
    target: { kind: "self" },
    effect: [{ kind: "heal", amount: 20 }],
    vfx: { color: "#7dffb3", particle: "glow", sound: "chime" },
  },
  toqueEletrico: {
    id: "toqueEletrico",
    name: "Toque Elétrico",
    tier: "common",
    cost: 15,
    cooldownMs: 4000,
    target: { kind: "instant" },
    effect: [{ kind: "stun", durationMs: 700 }],
    vfx: { color: "#f7ff5c", particle: "lightning", sound: "zap" },
  },
  investidaFeroz: {
    id: "investidaFeroz",
    name: "Investida Feroz",
    tier: "strong",
    cost: 30,
    cooldownMs: 7000,
    target: { kind: "self" },
    effect: [{ kind: "speedBuff", factor: 2, durationMs: 1500 }],
    vfx: { color: "#ff9d4f", particle: "trail", sound: "dash" },
  },
  domoDeProtecao: {
    id: "domoDeProtecao",
    name: "Domo de Proteção",
    tier: "strong",
    cost: 45,
    cooldownMs: 10000,
    target: { kind: "self" },
    effect: [{ kind: "heal", amount: 45 }],
    vfx: { color: "#9ad1ff", particle: "shield", sound: "hum" },
  },
  meteoro: {
    id: "meteoro",
    name: "Meteoro",
    tier: "super",
    cost: 90,
    cooldownMs: 40000,
    target: { kind: "projectile", speed: 18 },
    effect: [{ kind: "damage", amount: 90 }],
    vfx: { color: "#ff6b3b", particle: "nova", sound: "boom" },
  },
  tempestadeDeGelo: {
    id: "tempestadeDeGelo",
    name: "Tempestade de Gelo",
    tier: "super",
    cost: 85,
    cooldownMs: 40000,
    target: { kind: "area", radius: 8 },
    effect: [{ kind: "slow", factor: 0.3, durationMs: 4000 }],
    vfx: { color: "#c9f2ff", particle: "frost", sound: "windgust" },
  },
  teleporte: {
    id: "teleporte",
    name: "Teleporte",
    tier: "strong",
    cost: 30,
    cooldownMs: 9000,
    target: { kind: "self" },
    effect: [{ kind: "teleport", distance: 8 }],
    vfx: { color: "#c86bff", particle: "warp", sound: "blink" },
  },
  toqueVazio: {
    id: "toqueVazio",
    name: "Toque Vazio",
    tier: "common",
    cost: 12,
    cooldownMs: 1400,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 15 }],
    vfx: { color: "#7b5cff", particle: "spark", sound: "hit" },
  },
  infinito: {
    id: "infinito",
    name: "Infinito",
    tier: "common",
    cost: 15,
    cooldownMs: 5000,
    target: { kind: "self" },
    effect: [{ kind: "speedBuff", factor: 1.6, durationMs: 2000 }],
    vfx: { color: "#9ad1ff", particle: "shield", sound: "hum" },
  },
  efluvioRoxo: {
    id: "efluvioRoxo",
    name: "Eflúvio Roxo",
    tier: "strong",
    cost: 50,
    cooldownMs: 9000,
    target: { kind: "projectile", speed: 30 },
    effect: [{ kind: "damage", amount: 55 }],
    vfx: { color: "#b833ff", particle: "nova", sound: "boom" },
  },
  piscar: {
    id: "piscar",
    name: "Piscar",
    tier: "strong",
    cost: 25,
    cooldownMs: 6000,
    target: { kind: "self" },
    effect: [{ kind: "teleport", distance: 10 }],
    vfx: { color: "#c86bff", particle: "warp", sound: "blink" },
  },
  dominioVazio: {
    id: "dominioVazio",
    name: "Domínio: Vazio Infinito",
    tier: "super",
    cost: 110,
    cooldownMs: 50000,
    target: { kind: "area", radius: 12 },
    effect: [{ kind: "damage", amount: 100 }],
    vfx: { color: "#7b5cff", particle: "nova", sound: "boom" },
  },

  // John Kaisen (criado por Thiago) — mago de vazio/espaço/tempo: controle
  // e burst de dano à distância, sem chegar perto.
  rupturaDoVazio: {
    id: "rupturaDoVazio",
    name: "Ruptura do Vazio",
    tier: "common",
    cost: 18,
    cooldownMs: 3200,
    target: { kind: "projectile", speed: 22 },
    effect: [{ kind: "damage", amount: 22 }],
    vfx: { color: "#5b2a8c", particle: "nova", sound: "boom" },
  },
  passoFantasma: {
    id: "passoFantasma",
    name: "Passo Fantasma",
    tier: "common",
    cost: 20,
    cooldownMs: 7000,
    target: { kind: "self" },
    effect: [
      { kind: "heal", amount: 18 },
      { kind: "invisible", durationMs: 2200 },
    ],
    vfx: { color: "#8f7bd8", particle: "warp", sound: "blink" },
  },
  rupturaDoEspaco: {
    id: "rupturaDoEspaco",
    name: "Ruptura do Espaço",
    tier: "strong",
    cost: 45,
    cooldownMs: 9500,
    target: { kind: "projectile", speed: 26 },
    effect: [
      { kind: "damage", amount: 48 },
      { kind: "pull", distance: 4 },
    ],
    vfx: { color: "#3d1a5c", particle: "warp", sound: "boom" },
  },
  rupturaDoTempo: {
    id: "rupturaDoTempo",
    name: "Ruptura do Tempo",
    tier: "strong",
    cost: 50,
    cooldownMs: 11000,
    target: { kind: "area", radius: 6 },
    effect: [{ kind: "damage", amount: 30 }],
    // +60% de velocidade pra quem castou, além do dano em quem tiver perto.
    selfEffect: [{ kind: "speedBuff", factor: 1.6, durationMs: 2500 }],
    vfx: { color: "#7b5cff", particle: "shock", sound: "windgust" },
  },
  expansaoDeDominio: {
    id: "expansaoDeDominio",
    name: "Expansão de Domínio",
    tier: "super",
    cost: 115,
    cooldownMs: 55000,
    target: { kind: "area", radius: 14 },
    effect: [
      { kind: "damage", amount: 70 },
      { kind: "slow", factor: 0.25, durationMs: 4000 },
    ],
    vfx: { color: "#2a0f47", particle: "nova", sound: "boom" },
  },

  // Ronnie (criado por Daniel) — brigão bruto, sem magia: dano físico,
  // fúria e golpes de área que sacodem o chão.
  ronnieAtaqueBasico: {
    id: "ronnieAtaqueBasico",
    name: "Ataque Básico",
    tier: "common",
    cost: 15,
    cooldownMs: 2500,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 20 }],
    vfx: { color: "#ff9d4f", particle: "spark", sound: "hit" },
  },
  ativaRage: {
    id: "ativaRage",
    name: "Ativa Rage",
    tier: "common",
    cost: 30,
    cooldownMs: 14000,
    target: { kind: "self" },
    effect: [
      { kind: "damageBuff", factor: 1.5, durationMs: 5000 },
      { kind: "speedBuff", factor: 1.5, durationMs: 5000 },
    ],
    vfx: { color: "#ff3b1a", particle: "shock", sound: "dash" },
  },
  superTerremoto: {
    id: "superTerremoto",
    name: "Super Terremoto",
    tier: "strong",
    cost: 42,
    cooldownMs: 9000,
    target: { kind: "area", radius: 7 },
    effect: [
      { kind: "damage", amount: 35 },
      { kind: "stun", durationMs: 900 },
    ],
    vfx: { color: "#c97a3b", particle: "shock", sound: "boom" },
  },
  puloMortal: {
    id: "puloMortal",
    name: "Pulo Mortal",
    tier: "strong",
    cost: 48,
    cooldownMs: 10000,
    target: { kind: "area", radius: 5 },
    effect: [{ kind: "damage", amount: 40 }],
    lunge: 6, // salta pra frente ANTES da área resolver — acerta onde caiu
    castAnim: "NinjaJump_Start",
    vfx: { color: "#8b5a2b", particle: "nova", sound: "boom" },
  },
  choqueSismico: {
    id: "choqueSismico",
    name: "Choque Sísmico",
    tier: "super",
    cost: 115,
    cooldownMs: 55000,
    target: { kind: "area", radius: 13 },
    effect: [{ kind: "damage", amount: 85 }],
    knockback: 3.5,
    vfx: { color: "#ff4d1a", particle: "nova", sound: "boom" },
  },

  // Socos do botão esquerdo do mouse — uma receita por personagem (ver
  // CharacterDef.basicAttackId), custo 0, fora dos 5 slots. cooldownMs aqui
  // é o ritmo do combo: mais baixo = socos mais rápidos.
  // Físico, mas à distância — o soco tão forte que solta uma onda de corte
  // que viaja (ver createSlashMesh em Engine.ts, personagens "físicos" do
  // elenco: testador/guardiao/ronnie). Continua sem custo/mágica nenhuma,
  // só o alcance que mudou de corpo-a-corto pra projétil.
  testadorSoco: {
    id: "testadorSoco",
    name: "Soco",
    tier: "basic",
    cost: 0,
    cooldownMs: 380,
    target: { kind: "projectile", speed: 20 },
    effect: [{ kind: "damage", amount: 9 }],
    lunge: 1.2,
    knockback: 1,
    vfx: { color: "#ffffff", particle: "slash", sound: "hit" },
  },
  guardiaoSoco: {
    id: "guardiaoSoco",
    name: "Golpe",
    tier: "basic",
    cost: 0,
    cooldownMs: 650,
    target: { kind: "projectile", speed: 14 }, // mais lento, mas o golpe pesa
    effect: [{ kind: "damage", amount: 15 }],
    lunge: 0.8,
    knockback: 2, // mais lento, mas o golpe pesa — empurra mais longe
    vfx: { color: "#ffffff", particle: "slash", sound: "hit" },
  },
  senseiSoco: {
    id: "senseiSoco",
    name: "Toque",
    tier: "basic",
    cost: 0,
    cooldownMs: 260,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 6 }],
    lunge: 1.6,
    knockback: 0.5, // socos rápidos e fracos, mal empurram
    vfx: { color: "#7b5cff", particle: "spark", sound: "hit" },
  },
  johnKaisenSoco: {
    id: "johnKaisenSoco",
    name: "Golpe Amaldiçoado",
    tier: "basic",
    cost: 0,
    cooldownMs: 420,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 8 }],
    lunge: 1.1,
    knockback: 0.8,
    vfx: { color: "#5b2a8c", particle: "spark", sound: "hit" },
  },
  ronnieSoco: {
    id: "ronnieSoco",
    name: "Soco",
    tier: "basic",
    cost: 0,
    cooldownMs: 430,
    target: { kind: "projectile", speed: 17 },
    effect: [{ kind: "damage", amount: 11 }],
    lunge: 1,
    knockback: 1.2,
    vfx: { color: "#ffffff", particle: "slash", sound: "hit" },
  },

  // John Doe — artilheiro/demolidor: sem magia de verdade, é laser e
  // explosivo (raio contínuo, bomba de tempo, caixa que vira lava, ataque
  // orbital) fechando com um "fica grande" que também bate mais forte.
  johnDoeTiro: {
    id: "johnDoeTiro",
    name: "Tiro",
    tier: "basic",
    cost: 0,
    cooldownMs: 320,
    target: { kind: "projectile", speed: 27 },
    effect: [{ kind: "damage", amount: 7 }],
    lunge: 0.3,
    knockback: 0.4,
    vfx: { color: "#ff4d1a", particle: "spark", sound: "hit" },
  },
  raioLaserContinuo: {
    id: "raioLaserContinuo",
    name: "Raio Laser Contínuo",
    tier: "common",
    cost: 28,
    cooldownMs: 6500,
    // Linha reta fixa na direção do cast, 8 ticks de dano ao longo de
    // ~1.4s em vez de um acerto só (ver combat.ts/Engine.spawnLaserBeam).
    target: { kind: "beam", range: 22, tickMs: 180, durationMs: 1440 },
    effect: [{ kind: "damage", amount: 6 }],
    vfx: { color: "#ff4d1a", particle: "spark", sound: "zap" },
  },
  bombaRelogio: {
    id: "bombaRelogio",
    name: "Bomba-Relógio",
    tier: "common",
    cost: 30,
    cooldownMs: 9000,
    // durationMs 0 = um estouro só, 5s depois de plantada (ver
    // combat.ts/Engine.spawnZoneEffect).
    target: { kind: "zone", radius: 5, throwDistance: 6, delayMs: 5000, tickMs: 5000, durationMs: 0 },
    effect: [{ kind: "damage", amount: 30 }],
    knockback: 6, // "jogando todos" — o mais forte do elenco
    vfx: { color: "#ff4d1a", particle: "nova", sound: "boom" },
  },
  caixaDeLava: {
    id: "caixaDeLava",
    name: "Caixa de Lava",
    tier: "strong",
    cost: 44,
    cooldownMs: 11000,
    // Estoura rápido (telegraph de 900ms) e deixa uma poça ticando por 6s —
    // controle de área, não burst único.
    target: { kind: "zone", radius: 4.5, throwDistance: 5, delayMs: 900, tickMs: 700, durationMs: 6000 },
    effect: [{ kind: "damage", amount: 8 }],
    vfx: { color: "#ff6a1a", particle: "nova", sound: "boom" },
  },
  raioOrbital: {
    id: "raioOrbital",
    name: "Raio Laser Orbital",
    tier: "strong",
    cost: 48,
    cooldownMs: 12000,
    // Alcance bem maior que o resto do kit (throwDistance 16) — chamado à
    // distância, não plantado aos pés. vfx "lightning" já desenha um feixe
    // caindo do céu (ver particles.ts), serve perfeito de raio orbital.
    target: { kind: "zone", radius: 5.5, throwDistance: 16, delayMs: 550, tickMs: 550, durationMs: 0 },
    effect: [{ kind: "damage", amount: 40 }],
    vfx: { color: "#ff4d1a", particle: "lightning", sound: "boom" },
  },
  modoTitan: {
    id: "modoTitan",
    name: "Modo Titã",
    tier: "super",
    cost: 115,
    cooldownMs: 55000,
    target: { kind: "self" },
    effect: [
      { kind: "giant", scaleFactor: 1.9, durationMs: 10000 },
      { kind: "damageBuff", factor: 1.6, durationMs: 10000 },
    ],
    vfx: { color: "#ff4d1a", particle: "shock", sound: "boom" },
  },

  // Kaiman — brigão reptiliano: veneno (dano + lentidão) de perto e de
  // longe, fechando com uma transformação que fica gigante de verdade
  // (maior escala do elenco) e ainda cura no processo.
  kaimanGarra: {
    id: "kaimanGarra",
    name: "Garra",
    tier: "basic",
    cost: 0,
    cooldownMs: 400,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 12 }],
    lunge: 1,
    knockback: 1,
    vfx: { color: "#3ba24a", particle: "spark", sound: "hit" },
  },
  cuspeVenenoso: {
    id: "cuspeVenenoso",
    name: "Cuspe Venenoso",
    tier: "common",
    cost: 22,
    cooldownMs: 3500,
    target: { kind: "projectile", speed: 20 },
    effect: [
      { kind: "damage", amount: 16 },
      { kind: "slow", factor: 0.6, durationMs: 2000 },
    ],
    vfx: { color: "#5fd66b", particle: "spark", sound: "whoosh" },
  },
  pocaToxica: {
    id: "pocaToxica",
    name: "Poça Tóxica",
    tier: "common",
    cost: 30,
    cooldownMs: 8500,
    target: { kind: "zone", radius: 4.5, throwDistance: 5, delayMs: 700, tickMs: 800, durationMs: 5000 },
    effect: [
      { kind: "damage", amount: 7 },
      { kind: "slow", factor: 0.7, durationMs: 1500 },
    ],
    vfx: { color: "#3ba24a", particle: "nova", sound: "boom" },
  },
  mordidaBrutal: {
    id: "mordidaBrutal",
    name: "Mordida Brutal",
    tier: "strong",
    cost: 40,
    cooldownMs: 8000,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 42 }],
    lunge: 2,
    knockback: 2.5,
    vfx: { color: "#3ba24a", particle: "shock", sound: "hit" },
  },
  caudaVenenosa: {
    id: "caudaVenenosa",
    name: "Cauda Venenosa",
    tier: "strong",
    cost: 46,
    cooldownMs: 10000,
    target: { kind: "area", radius: 6 },
    effect: [
      { kind: "damage", amount: 30 },
      { kind: "slow", factor: 0.65, durationMs: 2000 },
    ],
    vfx: { color: "#5fd66b", particle: "nova", sound: "boom" },
  },
  furiaDoLagartoGigante: {
    id: "furiaDoLagartoGigante",
    name: "Fúria do Lagarto Gigante",
    tier: "super",
    cost: 120,
    cooldownMs: 58000,
    target: { kind: "self" },
    effect: [
      { kind: "giant", scaleFactor: 2.2, durationMs: 12000 },
      { kind: "damageBuff", factor: 1.7, durationMs: 12000 },
      { kind: "heal", amount: 45 },
    ],
    vfx: { color: "#3ba24a", particle: "shock", sound: "boom" },
  },

  // Blaze — controlador de fogo: piso em chamas e pilar são dano contínuo/
  // burst normais, mas o especial é DE PROPÓSITO desproporcional ao resto
  // do jogo (raio 45 — nenhuma outra habilidade chega nem perto), pedido
  // explícito de "explosão gigante que cobre o mapa inteiro".
  blazeSoco: {
    id: "blazeSoco",
    name: "Soco em Chamas",
    tier: "basic",
    cost: 0,
    cooldownMs: 360,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 10 }],
    lunge: 1.1,
    knockback: 1,
    vfx: { color: "#ff6a1a", particle: "spark", sound: "hit" },
  },
  rajadaDeFogo: {
    id: "rajadaDeFogo",
    name: "Rajada de Fogo",
    tier: "common",
    cost: 20,
    cooldownMs: 3200,
    target: { kind: "projectile", speed: 24 },
    effect: [{ kind: "damage", amount: 20 }],
    vfx: { color: "#ff6a1a", particle: "spark", sound: "whoosh" },
  },
  pisoEmChamas: {
    id: "pisoEmChamas",
    name: "Piso em Chamas",
    tier: "common",
    cost: 28,
    cooldownMs: 8500,
    target: { kind: "zone", radius: 4.5, throwDistance: 5, delayMs: 600, tickMs: 700, durationMs: 5500 },
    effect: [{ kind: "damage", amount: 8 }],
    vfx: { color: "#ff4500", particle: "nova", sound: "boom" },
  },
  ondaDeCalor: {
    id: "ondaDeCalor",
    name: "Onda de Calor",
    tier: "strong",
    cost: 42,
    cooldownMs: 9000,
    target: { kind: "area", radius: 6.5 },
    effect: [
      { kind: "damage", amount: 32 },
      { kind: "slow", factor: 0.7, durationMs: 1800 },
    ],
    vfx: { color: "#ff6a1a", particle: "shock", sound: "boom" },
  },
  pilarDeFogo: {
    id: "pilarDeFogo",
    name: "Pilar de Fogo",
    tier: "strong",
    cost: 48,
    cooldownMs: 11500,
    target: { kind: "zone", radius: 5.5, throwDistance: 14, delayMs: 700, tickMs: 700, durationMs: 0 },
    effect: [{ kind: "damage", amount: 46 }],
    vfx: { color: "#ff3300", particle: "nova", sound: "boom" },
  },
  combustaoTotal: {
    id: "combustaoTotal",
    name: "Combustão Total",
    tier: "super",
    cost: 125,
    cooldownMs: 60000,
    // Raio gigante de propósito (ver comentário acima) — cobre boa parte
    // do mapa, não só "uma área grande" como as outras supers.
    target: { kind: "area", radius: 45 },
    effect: [{ kind: "damage", amount: 65 }],
    knockback: 5,
    vfx: { color: "#ff4500", particle: "nova", sound: "boom" },
  },

  // Charuto Uzumaki — invocador: cada poder "chama" um bicho diferente.
  // Mecanicamente é dano em área com ticks (não uma IA própria de verdade,
  // ver Engine.spawnCompanions) mas os bichinhos aparecem de verdade,
  // orbitando o ponto onde foram chamados enquanto durar.
  seloDeChakra: {
    id: "seloDeChakra",
    name: "Selo de Chakra",
    tier: "basic",
    cost: 0,
    cooldownMs: 380,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 9 }],
    lunge: 1,
    knockback: 1,
    vfx: { color: "#ff9d1a", particle: "spark", sound: "hit" },
  },
  invocarRaposa: {
    id: "invocarRaposa",
    name: "Invocar Raposa",
    tier: "common",
    cost: 20,
    cooldownMs: 3000,
    target: { kind: "projectile", speed: 23 },
    effect: [{ kind: "damage", amount: 17 }],
    vfx: { color: "#ff8c3b", particle: "spark", sound: "whoosh" },
  },
  invocarCachorro: {
    id: "invocarCachorro",
    name: "Invocar Cachorro",
    tier: "common",
    cost: 24,
    cooldownMs: 6000,
    // Mordida rápida ao redor de mim — zone plantada em cima de mim mesmo
    // (throwDistance 0), um tick só (durationMs 0).
    target: { kind: "zone", radius: 4, throwDistance: 0, delayMs: 300, tickMs: 300, durationMs: 0 },
    effect: [{ kind: "damage", amount: 20 }],
    vfx: { color: "#8a5a2b", particle: "shock", sound: "boom" },
  },
  invocarLeao: {
    id: "invocarLeao",
    name: "Invocar Leão",
    tier: "strong",
    cost: 46,
    cooldownMs: 13000,
    target: { kind: "zone", radius: 7, throwDistance: 0, delayMs: 400, tickMs: 1200, durationMs: 12000 },
    effect: [{ kind: "damage", amount: 10 }],
    companions: ["#d4a83b"],
    vfx: { color: "#d4a83b", particle: "shock", sound: "boom" },
  },
  alcateia: {
    id: "alcateia",
    name: "Alcateia",
    tier: "strong",
    cost: 48,
    cooldownMs: 12000,
    target: { kind: "zone", radius: 8, throwDistance: 0, delayMs: 400, tickMs: 900, durationMs: 8000 },
    effect: [{ kind: "damage", amount: 12 }],
    companions: ["#ff8c3b", "#8a5a2b", "#d4a83b"],
    vfx: { color: "#ff9d1a", particle: "nova", sound: "boom" },
  },
  todosOsInvocados: {
    id: "todosOsInvocados",
    name: "Todos os Invocados",
    tier: "super",
    cost: 125,
    cooldownMs: 60000,
    target: { kind: "zone", radius: 10, throwDistance: 0, delayMs: 500, tickMs: 900, durationMs: 15000 },
    effect: [{ kind: "damage", amount: 16 }],
    companions: ["#ff8c3b", "#8a5a2b", "#d4a83b", "#ff8c3b", "#d4a83b"],
    vfx: { color: "#ff9d1a", particle: "nova", sound: "boom" },
  },
} satisfies Record<string, Ability>;

export type AbilityId = keyof typeof ABILITIES;

// Dados vindos de outro peer não são confiáveis — usar antes de indexar ABILITIES
// com um abilityId recebido pela rede (ver skill "review", seção DOM e segurança).
export function isAbilityId(value: string): value is AbilityId {
  return value in ABILITIES;
}
