import type { Ability } from "./types";

// Poderes de teste (personagem genérico) — só pra validar o sistema.
// Poderes de anime de verdade entram aqui depois, como novas receitas.
export const ABILITIES = {
  bolaDeEnergia: {
    id: "bolaDeEnergia",
    name: "Bola de Energia",
    tier: "common",
    cost: 20,
    cooldownMs: 3000,
    target: { kind: "projectile", speed: 25 },
    effect: [{ kind: "damage", amount: 25 }],
    vfx: { color: "#4fa3ff", particle: "spark", sound: "whoosh" },
  },
  golpeRapido: {
    id: "golpeRapido",
    name: "Golpe Rápido",
    tier: "common",
    cost: 10,
    cooldownMs: 1500,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 12 }],
    vfx: { color: "#ffffff", sound: "hit" },
  },
  ondaDeChoque: {
    id: "ondaDeChoque",
    name: "Onda de Choque",
    tier: "strong",
    cost: 40,
    cooldownMs: 8000,
    target: { kind: "area", radius: 5 },
    effect: [{ kind: "stun", durationMs: 1200 }],
    vfx: { color: "#ffb347", particle: "shock" },
  },
  passoRapido: {
    id: "passoRapido",
    name: "Passo Rápido",
    tier: "strong",
    cost: 15,
    cooldownMs: 6000,
    target: { kind: "self" },
    effect: [{ kind: "speedBuff", factor: 1.5, durationMs: 2000 }],
    vfx: { color: "#7dffb3", particle: "trail" },
  },
  explosaoDefinitiva: {
    id: "explosaoDefinitiva",
    name: "Explosão Definitiva",
    tier: "super",
    cost: 100,
    cooldownMs: 45000,
    target: { kind: "area", radius: 10 },
    effect: [{ kind: "damage", amount: 80 }],
    vfx: { color: "#ff3b3b", particle: "nova", sound: "boom" },
  },
  rajadaDeGelo: {
    id: "rajadaDeGelo",
    name: "Rajada de Gelo",
    tier: "common",
    cost: 15,
    cooldownMs: 4000,
    target: { kind: "projectile", speed: 20 },
    effect: [{ kind: "slow", factor: 0.5, durationMs: 2000 }],
    vfx: { color: "#8fe8ff", particle: "frost", sound: "chill" },
  },
  curaRapida: {
    id: "curaRapida",
    name: "Cura Rápida",
    tier: "common",
    cost: 25,
    cooldownMs: 5000,
    target: { kind: "self" },
    effect: [{ kind: "heal", amount: 20 }],
    vfx: { color: "#7dffb3", particle: "glow", sound: "chime" },
  },
  toqueEletrico: {
    id: "toqueEletrico",
    name: "Toque Elétrico",
    tier: "common",
    cost: 15,
    cooldownMs: 4000,
    target: { kind: "instant" },
    effect: [{ kind: "stun", durationMs: 700 }],
    vfx: { color: "#f7ff5c", particle: "lightning", sound: "zap" },
  },
  investidaFeroz: {
    id: "investidaFeroz",
    name: "Investida Feroz",
    tier: "strong",
    cost: 30,
    cooldownMs: 7000,
    target: { kind: "self" },
    effect: [{ kind: "speedBuff", factor: 2, durationMs: 1500 }],
    vfx: { color: "#ff9d4f", particle: "trail", sound: "dash" },
  },
  domoDeProtecao: {
    id: "domoDeProtecao",
    name: "Domo de Proteção",
    tier: "strong",
    cost: 45,
    cooldownMs: 10000,
    target: { kind: "self" },
    effect: [{ kind: "heal", amount: 45 }],
    vfx: { color: "#9ad1ff", particle: "shield", sound: "hum" },
  },
  meteoro: {
    id: "meteoro",
    name: "Meteoro",
    tier: "super",
    cost: 90,
    cooldownMs: 40000,
    target: { kind: "projectile", speed: 18 },
    effect: [{ kind: "damage", amount: 90 }],
    vfx: { color: "#ff6b3b", particle: "nova", sound: "boom" },
  },
  tempestadeDeGelo: {
    id: "tempestadeDeGelo",
    name: "Tempestade de Gelo",
    tier: "super",
    cost: 85,
    cooldownMs: 40000,
    target: { kind: "area", radius: 8 },
    effect: [{ kind: "slow", factor: 0.3, durationMs: 4000 }],
    vfx: { color: "#c9f2ff", particle: "frost", sound: "windgust" },
  },
  teleporte: {
    id: "teleporte",
    name: "Teleporte",
    tier: "strong",
    cost: 30,
    cooldownMs: 9000,
    target: { kind: "self" },
    effect: [{ kind: "teleport", distance: 8 }],
    vfx: { color: "#c86bff", particle: "warp", sound: "blink" },
  },
  toqueVazio: {
    id: "toqueVazio",
    name: "Toque Vazio",
    tier: "common",
    cost: 12,
    cooldownMs: 1400,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 15 }],
    vfx: { color: "#7b5cff", particle: "spark", sound: "hit" },
  },
  infinito: {
    id: "infinito",
    name: "Infinito",
    tier: "common",
    cost: 15,
    cooldownMs: 5000,
    target: { kind: "self" },
    effect: [{ kind: "speedBuff", factor: 1.6, durationMs: 2000 }],
    vfx: { color: "#9ad1ff", particle: "shield", sound: "hum" },
  },
  efluvioRoxo: {
    id: "efluvioRoxo",
    name: "Eflúvio Roxo",
    tier: "strong",
    cost: 50,
    cooldownMs: 9000,
    target: { kind: "projectile", speed: 30 },
    effect: [{ kind: "damage", amount: 55 }],
    vfx: { color: "#b833ff", particle: "nova", sound: "boom" },
  },
  piscar: {
    id: "piscar",
    name: "Piscar",
    tier: "strong",
    cost: 25,
    cooldownMs: 6000,
    target: { kind: "self" },
    effect: [{ kind: "teleport", distance: 10 }],
    vfx: { color: "#c86bff", particle: "warp", sound: "blink" },
  },
  dominioVazio: {
    id: "dominioVazio",
    name: "Domínio: Vazio Infinito",
    tier: "super",
    cost: 110,
    cooldownMs: 50000,
    target: { kind: "area", radius: 12 },
    effect: [{ kind: "damage", amount: 100 }],
    vfx: { color: "#7b5cff", particle: "nova", sound: "boom" },
  },

  // John Kaisen (criado por Thiago) — mago de vazio/espaço/tempo: controle
  // e burst de dano à distância, sem chegar perto.
  rupturaDoVazio: {
    id: "rupturaDoVazio",
    name: "Ruptura do Vazio",
    tier: "common",
    cost: 18,
    cooldownMs: 3200,
    target: { kind: "projectile", speed: 22 },
    effect: [{ kind: "damage", amount: 22 }],
    vfx: { color: "#5b2a8c", particle: "nova", sound: "boom" },
  },
  passoFantasma: {
    id: "passoFantasma",
    name: "Passo Fantasma",
    tier: "common",
    cost: 20,
    cooldownMs: 7000,
    target: { kind: "self" },
    effect: [
      { kind: "heal", amount: 18 },
      { kind: "invisible", durationMs: 2200 },
    ],
    vfx: { color: "#8f7bd8", particle: "warp", sound: "blink" },
  },
  rupturaDoEspaco: {
    id: "rupturaDoEspaco",
    name: "Ruptura do Espaço",
    tier: "strong",
    cost: 45,
    cooldownMs: 9500,
    target: { kind: "projectile", speed: 26 },
    effect: [
      { kind: "damage", amount: 48 },
      { kind: "pull", distance: 4 },
    ],
    vfx: { color: "#3d1a5c", particle: "warp", sound: "boom" },
  },
  rupturaDoTempo: {
    id: "rupturaDoTempo",
    name: "Ruptura do Tempo",
    tier: "strong",
    cost: 50,
    cooldownMs: 11000,
    target: { kind: "area", radius: 6 },
    effect: [{ kind: "damage", amount: 30 }],
    // +60% de velocidade pra quem castou, além do dano em quem tiver perto.
    selfEffect: [{ kind: "speedBuff", factor: 1.6, durationMs: 2500 }],
    vfx: { color: "#7b5cff", particle: "shock", sound: "windgust" },
  },
  expansaoDeDominio: {
    id: "expansaoDeDominio",
    name: "Expansão de Domínio",
    tier: "super",
    cost: 115,
    cooldownMs: 55000,
    target: { kind: "area", radius: 14 },
    effect: [
      { kind: "damage", amount: 70 },
      { kind: "slow", factor: 0.25, durationMs: 4000 },
    ],
    vfx: { color: "#2a0f47", particle: "nova", sound: "boom" },
  },

  // Ronnie (criado por Daniel) — brigão bruto, sem magia: dano físico,
  // fúria e golpes de área que sacodem o chão.
  ronnieAtaqueBasico: {
    id: "ronnieAtaqueBasico",
    name: "Ataque Básico",
    tier: "common",
    cost: 15,
    cooldownMs: 2500,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 20 }],
    vfx: { color: "#ff9d4f", particle: "spark", sound: "hit" },
  },
  ativaRage: {
    id: "ativaRage",
    name: "Ativa Rage",
    tier: "common",
    cost: 30,
    cooldownMs: 14000,
    target: { kind: "self" },
    effect: [
      { kind: "damageBuff", factor: 1.5, durationMs: 5000 },
      { kind: "speedBuff", factor: 1.5, durationMs: 5000 },
    ],
    vfx: { color: "#ff3b1a", particle: "shock", sound: "dash" },
  },
  superTerremoto: {
    id: "superTerremoto",
    name: "Super Terremoto",
    tier: "strong",
    cost: 42,
    cooldownMs: 9000,
    target: { kind: "area", radius: 7 },
    effect: [
      { kind: "damage", amount: 35 },
      { kind: "stun", durationMs: 900 },
    ],
    vfx: { color: "#c97a3b", particle: "shock", sound: "boom" },
  },
  puloMortal: {
    id: "puloMortal",
    name: "Pulo Mortal",
    tier: "strong",
    cost: 48,
    cooldownMs: 10000,
    target: { kind: "area", radius: 5 },
    effect: [{ kind: "damage", amount: 40 }],
    lunge: 6, // salta pra frente ANTES da área resolver — acerta onde caiu
    castAnim: "NinjaJump_Start",
    vfx: { color: "#8b5a2b", particle: "nova", sound: "boom" },
  },
  choqueSismico: {
    id: "choqueSismico",
    name: "Choque Sísmico",
    tier: "super",
    cost: 115,
    cooldownMs: 55000,
    target: { kind: "area", radius: 13 },
    effect: [{ kind: "damage", amount: 85 }],
    knockback: 3.5,
    vfx: { color: "#ff4d1a", particle: "nova", sound: "boom" },
  },

  // Socos do botão esquerdo do mouse — uma receita por personagem (ver
  // CharacterDef.basicAttackId), custo 0, fora dos 5 slots. cooldownMs aqui
  // é o ritmo do combo: mais baixo = socos mais rápidos.
  testadorSoco: {
    id: "testadorSoco",
    name: "Soco",
    tier: "basic",
    cost: 0,
    cooldownMs: 380,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 9 }],
    lunge: 1.2,
    knockback: 1,
    vfx: { color: "#ffffff", particle: "spark", sound: "hit" },
  },
  guardiaoSoco: {
    id: "guardiaoSoco",
    name: "Golpe",
    tier: "basic",
    cost: 0,
    cooldownMs: 650,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 15 }],
    lunge: 0.8,
    knockback: 2, // mais lento, mas o golpe pesa — empurra mais longe
    vfx: { color: "#ffffff", particle: "shock", sound: "hit" },
  },
  senseiSoco: {
    id: "senseiSoco",
    name: "Toque",
    tier: "basic",
    cost: 0,
    cooldownMs: 260,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 6 }],
    lunge: 1.6,
    knockback: 0.5, // socos rápidos e fracos, mal empurram
    vfx: { color: "#7b5cff", particle: "spark", sound: "hit" },
  },
  johnKaisenSoco: {
    id: "johnKaisenSoco",
    name: "Golpe Amaldiçoado",
    tier: "basic",
    cost: 0,
    cooldownMs: 420,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 8 }],
    lunge: 1.1,
    knockback: 0.8,
    vfx: { color: "#5b2a8c", particle: "spark", sound: "hit" },
  },
  ronnieSoco: {
    id: "ronnieSoco",
    name: "Soco",
    tier: "basic",
    cost: 0,
    cooldownMs: 430,
    target: { kind: "instant" },
    effect: [{ kind: "damage", amount: 11 }],
    lunge: 1,
    knockback: 1.2,
    vfx: { color: "#ffffff", particle: "spark", sound: "hit" },
  },
} satisfies Record<string, Ability>;

export type AbilityId = keyof typeof ABILITIES;

// Dados vindos de outro peer não são confiáveis — usar antes de indexar ABILITIES
// com um abilityId recebido pela rede (ver skill "review", seção DOM e segurança).
export function isAbilityId(value: string): value is AbilityId {
  return value in ABILITIES;
}
